export const TeamActionTypes = {
  TOGGLE_CREATE_TEAM_POPUP: "TOGGLE_CREATE_TEAM_POPUP",
  API: "API",
  SET_ALL_TEAM: "SET_ALL_TEAM",
  RESET_USER_INFO: "RESET_USER_INFO",
  ADD_TEAM: "ADD_TEAM",
  REMOVE_TEAM: "REMOVE_TEAM",
  UPDATE_TEAM: "UPDATE_TEAM",
  ADD_TO_MEMBERS: "ADD_TO_MEMBERS",
};
