export const InviteActionTypes = {
  TOGGLE_SEARCH_DORBDOWN: "TOGGLE_SEARCH_DORBDOWN",
  API: "API",
  SET_ALL_USERS: "SET_ALL_USERS",
  ADD_MEMBERS: "ADD_MEMBER",
  REMOVE_MEMBERS: "REMOVE_MEMBER",
};
