export const BoardActionTypes = {
  TOGGLE_CREATE_BOARD_POPUP: "TOGGLE_CREATE_BOARD_POPUP",
  API: "API",
  SET_ALL_BOARDS: "SET_ALL_BOARDS",
  SELECTED_BOARD: "SELECTED_BOARD",
  ADD_BOARD: "ADD_BOARD",
  REMOVE_BOARD: "REMOVE_BOARD",
  UPDATE_BOARD: "UPDATE_BOARD",
  RESET_USER_INFO: "RESET_USER_INFO",
};
