export const CardActionTypes = {
  TOGGLE_CARD_FORM: "TOGGLE_CARD_FORM",
  TOGGLE_CARD_OPTION: "TOGGLE_CARD_OPTION",
  API: "API",
  SET_ALL_CARD: "SET_ALL_CARD",
  ADD_CARD: "ADD_CARD",
  REMOVE_CARD: "REMOVE_CARD",
  UPDATE_CARD: "UPDATE_CARD",
  RESET_USER_INFO: "RESET_USER_INFO",
  DRAG_Card_HAPPENED: "DRAG_Card_HAPPENED",
  DRAG_Card_END: "DRAG_Card_END",
};
