export const ListActionTypes = {
  TOGGLE_LIST_FORM: "TOGGLE_LIST_FORM",
  API: "API",
  SET_ALL_LIST: "SET_ALL_LIST",
  ADD_LIST: "ADD_LIST",
  ADD_CARDID: "ADD_CARDID",
  REMOVE_LIST: "REMOVE_LIST",
  UPDATE_LIST: "UPDATE_LIST",
  RESET_USER_INFO: "RESET_USER_INFO",
  DRAG_HAPPENED: "DRAG_HAPPENED",
};
