export const UserActionTypes = {
  TOGGLE_ACCOUNT_DORPDOWN: "TOGGLE_ACCOUNT_DORPDOWN",
  API: "API",
  SET_USER_INFO: "SET_USER_INFO",
  SET_USER_PROFILE: "SET_USER_PROFILE",
  RESET_USER_INFO: "RESET_USER_INFO",
};
